Algoritmo "MediaNotas"
Var
    NotaA, NotaB, NotaC, NotaD, Media: Real

Inicio
      Escreva("Informe a Primeira Nota: ")
      Leia(NotaA)

      Escreva("Informe a Segunda Nota: ")
      Leia(NotaB)
      
      Escreva("Informe a Terceira Nota: ")
      Leia(NotaC)
      
      Escreva("Informe a Quarta Nota: ")
      Leia(NotaD)
      
      Media <- (NotaA + NotaB + NotaC + NotaD) / 4
      
      Escreval("A Media De Notas Foi: ", Media)



Fimalgoritmo