Algoritmo "TiposDevariaveis"
Var
   modelo: Caractere
   Ano: Inteiro
   Valor: Real
   IpvaPago: Logico
   SeguroPago: logico

Inicio
      Modelo <- "Gol"
      Ano <- 2010
      Valor <- 20500.14
      IpvaPago <- Falso
      SeguroPago <- Verdadeiro

       Escreval(Modelo)
       Escreval(Ano)
       Escreval(Valor)
       Escreval(IpvaPago)
       Escreval(SeguroPago)
       
Fimalgoritmo