Algoritmo "semnome"
Var

     Abacate, Melancia,TotalFrutasSacola: Inteiro
Inicio
      // Declarando variaveis
      Abacate <- 2
      Melancia <- 3
      
      // Declarando Variavel Da Soma
      TotalFrutasSacola <- Abacate + Melancia
      
      //trocando o valor da variavel abacate
      Abacate <- 5
      
      //Somando Novamente
      TotalFrutasSacola <- Abacate + Melancia
      
      // Imprimindo Resultado
      Escreva(TotalFrutasSacola)


Fimalgoritmo